
const BestWebAgencyInRabat = [
  {
    companyName: 'Pixels Trade',
    link: 'https://www.pixelstrade.com/?utm_source=sortlist&utm_medium=profile&utm_campaign=https%3A%2F%2Fwww.sortlist.com%2Fweb-design%2Frabat-rabat-sale-zemmour-zaer-ma',
    email:'info@pixelstrade.com',

  },
  {
    companyName: 'E-Novation',
    link: 'https://www.e-novation.ma/',
    email:'contact@e-novation.ma',

  },
  {
    companyName: 'DigiTransform',
    link: 'https://digitransform.co/',
    email:'contact@digitransform.co',

  },
  {
    companyName: 'ThinkWeb',
    link: 'https://thinkweb.ma/',
    email:'contact@thinkweb.ma',
  },
  {
    companyName: 'Majjane',
    link: 'https://majjane.ma',
    email:'contact@majjane.ma',
  },
  {
    companyName:'Central Web',
    link:'https://www.centralweb.ma/',
    email:'contact@centralweb.ma'
  },
  {
    companyName:'EmaVeo',
    link: '  https://emaveo.com/',
    email:'contact@emaveo.com'
  },
  {
    companyName:'Digency',
    link:'https://www.digency.ma/',
    email:'info@digency.ma',
  },
  {
    companyName:'ReWeb',
    link:'https://www.reweb.ma/',
    email: 'contact@reweb.ma',
  },
  {
    companyName:'NTV',
    link:'https://ntv.ma/',
    email:'contact@ntv.ma',
  },
  {
    companyName:'NieMe',
    link:'https://www.niemeconseil.ma/',
    email:'info@niemeconseil.ma'
  },
  {
    companyName:'fornetmaroc',
    link:'https://www.fornetmaroc.com/',
    email:'recrutement@fornetmaroc.com'
  },
  {
    companyName:'Inovat',
    link:'https://inovat.ma/',
    email:'contact@inovat.ma'
  }
];

const AU = [
    'filler@godaddy.com',
    'montreal@bab-canada.com',
    'contact@fornetmaroc.com'
];


const UKLONDONEMAILS = [
    'ramesh.shashmith@gmail.com',
    'hanguy.work89@gmail.com',
    'stellamarina5@gmail.com',
    'sai.avance@gmail.com',
    'yolaine@gmail.com',
    'hema1531992@gmail.com',
    'myhrcareers@gmail.com',
    'ildikohorvathhungary@gmail.com',
    'angelasanchezcoach@gmail.com',
    'amieleecoaching@gmail.com',
    'synergistech@gmail.com',
    'bianca.cmartin@gmail.com',
    'darren.miller.hr@gmail.com',
    'borgia.stellario@gmail.com',
    'chris.oak1960@gmail.com',
    'hilaryculkin@gmail.com',
    'gfitz999@gmail.com',
    'hrmanagercipd@gmail.com',
    'darek.dankowski@gmail.com',
    'michaeljonesrectraining@gmail.com',
    'florence.haessler@gmail.com',
    'sarahfeyaz@gmail.com',
    'mc.volken@gmail.com',
    'johnbevan1@gmail.com',
    'catherine.ward.ppl@gmail.com',
    'nereacastilloasin@gmail.com',
    'aravvall@gmail.com',
    'dave911sos@gmail.com',
    'andrew.branfield@gmail.com',
    'melyjm89@gmail.com',
    'yoliharel@gmail.com',
    'kandivali.hr@gmail.com',
    'imrannewrekar18@gmail.com',
    'skillwox@gmail.com',
    'gjpheiffer@gmail.com',
    'asaakanksha24@gmail.com',
    'josh@jbhtech.org.il',
    'undiscoveredskill@gmail.com',
    'twumnelson@gmail.com',
    'divakarkumars@gmail.com',
    'lukapilipovic25@gmail.com',
    'rikus.oswald@gmail.com',
    'gourki731@gmail.com',
    'hyndmanpatria@gmail.com',
    'am3948104@gmail.com',
    'graeme.alford@gmail.com',
    'elishablevy@gmail.com',
    'ahmedmoyahaya70@gmail.com',
    'shuja9810@gmail.com',
    'linasalerno79@gmail.com',
    'lizziebutchercoaching@gmail.com',
    'jessicasoothill0407@gmail.com',
    'tapaskumar.roy611@gmail.com',
    'chethangovindaraj@gmail.com',
    'ellen.mar.book@gmail.com',
    'career.hajoori@gmail.com',
    'mmeeofficial@gmail.com',
    'yuliadikareva@gmail.com',
    'gmarcondesbd@gmail.com',
    'fady.kadry@gmail.com',
    'ekaterinakolyagina@gmail.com',
    'charliesaidthat@gmail.com',
    'lukasrastovic@gmail.com',
    'jpradeep.chandar@gmail.com',
    'e.legeindre@gmail.com',
    'henarchconltd@gmail.com',
    'simonclarkwriting@gmail.com',
    'nikoletta.velentza@gmail.com',
    'tenyjk@gmail.com',
    'ajithvenky.m@gmail.com',
    'starkemarcus@gmail.com',
    'marian.baran9@gmail.com',
    'maryamdatti1@gmail.com',
    'asif83online@gmail.com',
    'anastasiatrust@gmail.com',
    'antontrusts@gmail.com',
    'muenlee.th@gmail.com',
    'cookie.th@gmail.com',
    'adnanghani6@gmail.com',
    'seanhreynolds@gmail.com',
    'visaa1consultant@gmail.com',
    'kumarimeena55@gmail.com',
    'ma.globalrecruiters@gmail.com',
    'marif5756484@gmail.com',
    'jirapat1st@gmail.com',
    'danielle.jurman@gmail.com',
    'emilydsmith1@gmail.com',
    'charlesbrunoeze@gmail.com',
    'newlandsresidentsassoczim@gmail.com',
    'szabian.ali@gmail.com',
    'molliebolton42@gmail.com',
    'orsoporta@gmail.com',
    'mizbah.ahsan@gmail.com',
    'czech.ania@gmail.com',
    'vsuppiah.gamechange@gmail.com',
    'sha@timesconsult.com',
    'glaubiasales01@gmail.com',
    'annemarie.mostard1965@gmail.com',
    'drewspink12@gmail.com'
  ];


  const fakeCompaniesData = [
    { id: 1, name: 'Company A', avatar: 'companyA.jpg' },
    { id: 2, name: 'Company B', avatar: 'companyB.jpg' },
    // Add more fake companies as needed
  ];

  
  const UKMANCHESTER = [
    'recruitereliteltd@gmail.com',
    'foodconsultant.aq@gmail.com',
    'michele1972.mn@gmail.com',
    'alan.nutter@gmail.com',
    'ljtinsleyuk@gmail.com',
    'andybellcareers@gmail.com',
    'jessica.f.whyte@gmail.com',
    'gonzymartins@gmail.com',
    'leda.tustin@gmail.com',
    'nigelashread@gmail.com',
    'rebeccalynnbarter@gmail.com',
    'helengrantham66@gmail.com',
    'drivesafesouthwest@gmail.com',
    'kpochin68@gmail.com',
    'malamah68@yahoo.co.uk',
    'sjbloorconsulting@gmail.com',
    'sharon.bloor26@gmail.com',
    'ekommandy@gmail.com',
    'denise.exley1@gmail.com',
    'carolannmaynard6@gmail.com',
    'davidharding1986@gmail.com',
    'www.leegarnettocl@gmail.com',
    'oakdenepl@gmail.com',
    'graham.ball@adaptfinance.co.uk',
    'dawid.adam.jaworski@gmail.com',
    'glenthefloorlayer@gmail.com',
    'skinsilkhenna@gmail.com',
    'pollyewinder@gmail.com',
    'amineeddibi1@gmail.com',
    'am3948104@gmail.com',
    '21stockburn@gmail.com',
    'patchwork.enquiry@gmail.com',
    'sarahtommins798@gmail.com',
    'nkkalu6@gmail.com',
    'norcalrecruiter@gmail.com',
    'djuganski@gmail.com',
    'nikhil.c.lakhani@gmail.com',
    'diegoedulage@gmail.com',
    'csawcyp@gmail.com',
    'rebeccajeffrey89@gmail.com',
    'raddystamenov@gmail.com',
    'kirsty.kerins11@gmail.com',
    'ajbennett1985@gmail.com',
    'bsheerkheder77@gmail.com',
    'asifseneer@gmail.com',
    'matthewchristian95@gmail.com',
    'winningsaint@gmail.com',
    'arcangeladvertising@gmail.com',
    'amieleecoaching@gmail.com',
    'tariq.hussain6110@gmail.com',
    'www.siggybyoga@gmail.com',
    'oscarmartinperez@gmail.com',
    'dorrian.sidwell@gmail.com',
    'helga.addeo89@gmail.com',
    'catherine.odonohoe@gmail.com',
    'davidarthurhughes@gmail.com',
    'samben1@gmail.com',
    'marcbradley.artwork@gmail.com',
    'leemccullagh@gmail.com',
    'synergistech@gmail.com',
    'bagnol12@gmail.com',
    'talktojvmcgrath@gmail.com',
    'olu.bamgbade@gmail.com',
    'thebroaduk@gmail.com',
    'bethfrackelton@gmail.com',
    'mmazullah@gmail.com',
    'saumacollective@gmail.com',
    'wjwalker@ntlworld.com',
    'wjwalker643@gmail.com',
    'avg0687@gmail.com',
    'davidrose088@gmail.com',
    'roma.czarnocka@gmail.com',
    'vincesopra@gmail.com',
    'liviuschipor6@gmail.com',
    'katarinavelika00@gmail.com',
    'eightink8@gmail.com',
    'estherfreeman@gmail.com',
    'posterkid.enquiries@gmail.com',
    'info.bobcats.org@gmail.com',
    'alexandra28smith@gmail.com',
    'aghaider@gmail.com',
    'cdahwa@gmail.com',
    'richardlocketdesign@gmail.com',
    'foodlinea@gmail.com',
    'yvonnecanizales@gmail.com',
    'stephan.mangin@gmail.com',
    'uram.emily@gmail.com',
    'mmeeofficial@gmail.com',
    'nuranfraser16@gmail.com',
    'mccarthy.j.rachel@gmail.com',
    'rinkugoenka2206@gmail.com',
    'canham.ann1e@gmail.com',
    'galolx@gmail.com',
    'tha1originalmixmasterprecise@gmail.com',
    'minnyungh@gmail.com',
    'connectcosmosbusinesssolutions@gmail.com',
    'fareed.alkholoq@gmail.com',
    'hanisjamaluddin05@gmail.com',
    'cengalknajidemail@gmail.com',
    'enqueries.ani@gmail.com',
    'bernicemiler@gmail.com'
  ];
  
  
  const FRPARIS = [
    'arthur.alfonsi@gmail.com',
    'clark.willj@gmail.com',
    'headhunter@gmail.com',
    'thiago.bornioti@gmail.com',
    'rdevaucorbeil@gmail.com',
    'beverley.ebara@gmail.com',
    'marysth@gmail.com',
    'cedric.laforge@gmail.com',
    'heriko.gaming@gmail.com',
    'insurancebyparis@gmail.com',
    'e.legeindre@gmail.com',
    'alexis.milcent@gmail.com',
    'abdelbar.negoce@gmail.com',
    'ja.pavlasova@gmail.com',
    'alix.ligot@gmail.com',
    'patricia.arul@gmail.com',
    'guada.costillas@gmail.com',
    'my.arafa.alaoui@gmail.com',
    'cabineticd@gmail.com',
    'cfdtinhni@gmail.com',
    'nejproductionsus@gmail.com',
    'elalamisofya@gmail.com',
    'damir.medvesek@gmail.com',
    'ziyad.bekkaoui@gmail.com',
    'patricio.r.saldivia@gmail.com',
    'ekpodilemaxime@gmail.com',
    'doan.celine@gmail.com',
    'cgscout@gmail.com',
    'mccggroup@gmail.com',
    'lenaic.aoustin@gmail.com',
    'donnalilinda@gmail.com',
    'ghazi.amina13@gmail.com',
    'folaesan@gmail.com',
    'mahy.elisabeth@gmail.com',
    'thomas.allot92@gmail.com',
    'texprint93@gmail.com',
    'flon.victor@gmail.com',
    'sumeesh.sumi82@gmail.com',
    'shielaza@gmail.com',
    'gershmanliubov@gmail.com',
    'dorotheeroberts@gmail.com',
    'technicalrecruiter777@gmail.com',
    'sandrinehairstylist@gmail.com',
    'aridayan24@gmail.com',
    'maymoon1407@gmail.com',
    'dr.nezar717@gmail.com',
    'deepshika.yadugiri_2023@woxsen.edu.in',
    'charlottenerriere@gmail.com',
    'phareservicesadomicile@gmail.com',
    'eliane.dellanna@gmail.com',
    'krsadati@gmail.com',
    'eduardoayuso@gmail.com',
    'mohammed.erregragui@gmail.com',
    'carole.foglia.bom@gmail.com',
    'francesco.latorre@gmail.com',
    'alicejurios@gmail.com',
    'segolene.rpforu@gmail.com',
    'vanessaodile0@gmail.com',
    'ericv.nc@gmail.com',
    'mariem.dabboussi@gmail.com',
    'vaikezas12@gmail.com',
    'portasrhommel@gmail.com',
    'abhishekjain1910@gmail.com',
    'ndewitte2020@gmail.com',
    'dlucasformation@gmail.com',
    'bikantus@gmail.com',
    'sornewngim@gmail.com',
    'vincent.scobart@gmail.com',
    'elina.aarela@gmail.com',
    'chantal.dorn@gmail.com',
    'heckmann.gerardo@gmail.com',
    'elsa.gomis@gmail.com',
    'raho.giuseppe83@gmail.com',
    'etbiju2010@gmail.com',
    'sarahwallaceart@gmail.com',
    'milurakotonirainy@gmail.com',
    'agronaturalpark@gmail.com',
    'his.jeremy@gmail.com',
    'ines.boursot@gmail.com',
    'sdg2030award@gmail.com',
    'shankarbaba@gmail.com',
    'chendatuy@gmail.com',
    'ctoc.society@gmail.com',
    'khaled.kechroud@gmail.com',
    'elhadjiassane.tall@campus.cfpb.fr',
    'xavier.bourin44@gmail.com',
    'broadwayalbania@gmail.com',
    'dima33687@gmail.com',
    'annemjfnijs@gmail.com',
    'kirshz123@gmail.com',
    'colnpsingh@gmail.com',
    'adrian.ecltd@gmail.com',
    'info.vincentmichel@gmail.com',
    'starhomz1@gmail.com',
    'doragabrielacia@gmail.com',
    'ariane.clergue@gmail.com',
    'ahmedtekar@gmail.com',
    'faezemolapanah@gmail.com',
    'nika.matic14@gmail.com',
    '3coinslabels@gmail.com',
    'benjamintoulemonde@gmail.com',
    'valmallecamille@gmail.com',
    'cesarcorro.sn@gmail.com',
    'ramesh106.m@gmail.com',
    'micica.studio@gmail.com',
    'projekty.info.kc@gmail.com',
    'marine.francois85@gmail.com',
    'friophotography@gmail.com',
  ];
  
  
  //not use it Above 
  
  
  const emailArray = [
    'hrconnect.com@gmail.com',
    'hadani.mohamed2014@gmail.com',
    'www.chahbouni.yassine@gmail.com',
    'bouchaouir.sara@gmail.com',
    'elmarzoukighita@gmail.com',
    'salimafares2@gmail.com',
    'hanane@gmail.com',
    'bakhayi.taoufik@gmail.com',
    'mr.essadik.yassine@gmail.com',
    'm656269@gmail.com',
    'y.ilyasse@gmail.com',
    'youssef.alami94@gmail.com',
    'elalamisofya@gmail.com',
    'rimammor1@gmail.com',
    'soufianfraidi@gmail.com',
    'lazimikhawla66@gmail.com',
    'ae.fadilis@gmail.com',
    'hanaa.idrissi@gmail.com',
    'abdelkrim.benamer@abenpartners.com',
    'haidimohamed@gmail.com',
    'youssefadid@gmail.com',
    'jawahir.chaabi@gmail.com',
    'samirbennani18samirbennani18@gmail.com',
    'maoukan.tarik@gmail.com',
    'elaounistam@gmail.com',
    'bazidkhalid44@gmail.com',
    'abdelouahed.brir@gmail.com',
    'hajarasouab@gmail.com',
    'err.abdelhak@gmail.com',
    'khouloud.kebali@gmail.com',
    'fluidesystemes@gmail.com',
    'sandal3@gmail.com',
    'simo.sh123.ss@gmail.com',
    'ghazi.amina13@gmail.com',
    'elhoussinemoussaidelidrissi@gmail.com',
    'belaraj.hamza@outlook.com',
    'belaraj.hamza@gmail.com',
    'sparkdesign20@gmail.com',
    '644000.34.benlhaj.rachid@gmail.com',
    'hamza.chbouki@gmail.com',
    'saadelabbassiofficial@gmail.com',
    'k.touimi.benjelloun@gmail.com',
    'otmane.hz@gmail.com',
    'abdobenha7@gmail.com',
    'benelmalihkhadija@gmail.com',
    'mohamed.bouigazouane@gmail.com',
    'glennwoerz@gmail.com',
    'elkettanikenza027@gmail.com',
    'abdelhadi.laayouni3@gmail.com',
    'abdel04safadi@gmail.com',
    'bakrimw@gmail.com',
    'nihadbeautyd@gmail.com',
    'elkharras.yousra@gmail.com',
    'sebastien.climaxconseils@gmail.com',
    'hamouda1989carisr@gmail.com',
    'aimadelkourchi6@gmail.com',
    'amouri.adil@gmail.com',
    'benhamma12.qw@gmail.com',
    'abachoukri@gmail.com',
    'mhammoumi96@gmail.com',
    'investigateurprive8@gmail.com',
    'elmehditougani@gmail.com',
    'abdessadeq.said@gmail.com',
    'emmapdodo@gmail.com',
    'hassanidballa50@gmail.com',
    'moroccogumanyes@gmail.com',
    'aitmlouk@gmail.com',
    'hamidkechna@gmail.com',
    'walid.barka@gmail.com',
    'kodja.elvis@gmail.com',
    'ess.asmaa@gmail.com',
    'satabdibba1@gmail.com',
    'gastonbiyiga@gmail.com',
    'shahla.rinaldi@gmail.com',
    'bhaskarsh85@gmail.com',
    'media.star.agancy@gmail.com',
    'vanessaicbaiao@gmail.com',
    'blitzbusiness.co@gmail.com',
    'davy.theophile@gmail.com',
    'israeltagba@gmail.com',
    'myriam.ramy@gmail.com',
    'axelcthoinon@gmail.com',
    'mgt.ali20@gmail.com',
    'frederico.santos.ribeiro@gmail.com',
    'soso.creative.director@gmail.com',
    'mohsen6094@gmail.com',
    'salmoun.ilyes@gmail.com',
    'happynass2014@gmail.com'
  ];
  
  
  const ListOfCompaniesOfCanada = ['youneshero436@gmail.com', 
  "gouldiead@gmail.com",
"ankitbansal101@gmail.com",
"destahaile73@gmail.com",
"mikemigueldiaz@gmail.com",
"shieldservice@gmail.com",
"cms.it.mgmtservices@gmail.com",
"contact@infotechwebonline.com",
"rolf88kayak@gmail.com",
"ankitmonapara1993@gmail.com",
"yuliyapakhalchuk@gmail.com",
"a.hilabi7@gmail.com",
"bullelusive@gmail.com",
  'info@abrimex.com',
  'info@acces-cible.org',
  'reception@accestravail.qc.ca',
  'info@lesacados.org',
  'info@adnemploi.com',
  'info@aimcroitqc.org',
  'info@alac.qc.ca',
  'info@AllianceCT.ca',
  'info@alphabellechasse.com',
  'reception@midi40.com',
  'info@ape.qc.ca',
  'admin@atmprq.com',
  // start in just one company
  'communication@aslm.ca', 
  'edufort@aslm.ca',
  'rchartier@aslm.ca',
  'amcalice@aslm.ca',
  'memadore@aslm.ca',
  // end in just one company
  'info@boisurbain.org',
  'info@bae.qc.ca',
  'info@ea-cd.ca',
  'admin@atmprq.com',
  'info@boisurbain.org',
  'info@toncec.ca',
  'info@carrefouremploilotbiniere.com',
  'administration@cje-abc.qc.ca',
  'info@cje-arthabaska.ca',
  'info@cjechateauguay.org',
  'acton@cjejohnson.org',
  'info@cjeae.qc.ca',
  'info@cjea.org',
  'info@cjecn.qc.ca',
  'cjel@cjelislet.qc.ca',
  'info@cjedm.qc.ca',
  'info@cjevg.qc.ca',
  'info@cjemirabel.ca',
  'info@cje-pierredesaurel.com',
  'info@cje-rdp.org',
  'cplourde@cjedesbleuets.ca',
  'info@cjemoulins.org',
  //start one company
  'asbestos@cjerichmond.qc.ca',
  'richmond@cjerichmond.qc.ca',
  'warwick@cjerichmond.qc.ca',
  // end one company 
  'info@cjeso-mtl.org',
  'info@cjeoptionemploi.org',
  'info-stremi@cjehuntingdon.org',
  'info@cjehuntingdon.org',
  'info@cjemaskinonge.qc.ca',
  'cjepapineau@cjepapineau.qc.ca',
  'emploi@cjesh.org',
  'cje@cjestlaurent.org',
  'info@cjevs.org',
  'info@cjeanjou.com',
  'carrefour@cjeb-s.ca',
  'info@cje-centrenord.com',
  'reception@cjecc.org',
  //start one company 
  'direction@cjenicbec.org',
  'coordination_liaison@cjenicbec.org',
  'administration@cjenicbec.org',
  'anadeau@cjenicbec.org',
  'agentmilieu@cjenicbec.org',
  'jcossette@cjenicbec.org',
  'jdesmarais_godon@cjenicbec.org',
  'conseilleremploi2@cjenicbec.org',
  'ppowers@cjenicbec.org',
  'crheault@cjenicbec.org',
  'slarocque@cjenicbec.org',
  'migrationny@cjenicbec.org',
  'immigration@cjenicbec.org',
  'mboisvert@cjenicbec.org',
  'agentplaceauxjeunes@cjenicbec.org',
  'eimbeault@cjenicbec.org',
  //start one company
  'CJE@CJENICBEC.ORG',
  //end one company
  'cje.st-jean@cje-isj.com',
  'cje.marieville@cje-isj.com',
  'cje.farnham@cje-isj.com',
  'cje@cje-sherbrooke.qc.ca',
  'cje@cjebeauce-sud.com',
  'info@cjecdn.qc.ca',
  'info@moncje.com',
  // start one company
  'accueil@cjed.qc.ca',
  'cjehsp@cjed.qc.ca',
  'ce.portcartier@cjed.qc.ca',
  //end one company 
  'info@cjeouestile.qc.ca',
  'info@cjeo.qc.ca',
  'info@cjejamesie.ca',
  'claudie@cjejamesie.ca',
  'nicolas@cjejamesie.ca',
  'info@cjejamesie.ca',
  'christine@cjejamesie.ca',
  'info@cjemontmagny.com',
  'accueil@cjecotedegaspe.ca',
  'cje-manic@cjemanic.com',
  'cje@portneufplus.com',
  'info@cjetemiscouata.qc.ca',
  'info@cjeverdun.org',
  'cjed@cgocable.ca',
  'accueil@cjet.qc.ca',
  'cjehm@cjehm.org',
  'info@cjela.qc.ca',
  'info@cjeetchemins.ca',
  
  ];
  
  const NewListOfCanada = [  'info@cjemontreal.org',
  'info@groupeinclusia.com',
  'info@groupeinclusia.com',
  'accueil@gcsd.qc.ca',
  'transport@grenierpopulaire.com',
  'info@grenierpopulaire.com',
  'gitcre@git.qc.ca',
  'example@tucompany.com',
  'contact@gestionjeunesse.org',
  'info@yesmontreal.ca',
  'info@espacepivot.ca',
  'reception@espacepivot.ca',
  'responsableconfidentialite@espacepivot.ca',
  'headconfidentialite@espacepivot.ca',
  'info@formationdimensions.com',
  'info@recypro.com',
  'boutique@recypro.com',
  'ressourcerie@recypro.com',
  //email i never send to them is above
  'info@cjern.qc.ca',
  'INFO@CJE-NDG.COM',
  'accueil@cjer.ca',
  'INFO@CJESAG.QC.CA',
  'info@cje-tdb.qc.ca',
  'info@cjetrdc.com',
  'info@cje-tdb.qc.ca',
  'info@tyndalestgeorges.com',
  'info@caecapital.com',
  'info@caehyr.com',
  'info@capemploi.ca',
  'info@caavd.ca',
  'rendezvous@caci-bc.org',
  'info@lajonction.org',
  'info@cime-emploi.com',
  'vmonette@cielaurentides.com',
  'info@cimoi.com',
  'info@cipl.ca',
  'st-eustache@cible-emploi.qc.ca',
  'ste-therese@cible-emploi.qc.ca',
  'st-hubert@coffre.ca',
  'atelier@atelierfspn.org',
  'atelier@atelierfspn.org',
  'info@optiontravail.com',
  'info@crecdn.com',
  'info@crepointeclaire.com',
  'contact@actionrh.ca',
  // start one company
  'micheline.deslauriers@opexemploi.com',
  'bruno.pare@opexemploi.com',
  'aline.maltais@opexemploi.com',
  'sylvie.haman@opexemploi.com',
  'sabrina.huppe@opexemploi.com',
  'danielle.turcotte@opexemploi.com',
  'jeanne.lambert@opexemploi.com',
  'charles.racine@opexemploi.com',
  'edith.dubois@opexemploi.com',
  'isabelle.martin@opexemploi.com',
  'pajicgranby@opexemploi.com',
  'patricia.meunier@opexemploi.com',
  'caroline.cossette@opexemploi.com',
  'jennyfer.gosselin@opexemploi.com',
  'nathalie.ricard@opexemploi.com',
  'isabelle.martin@opexemploi.com',
  'info@opexemploi.com',
  // end one company 
  'webmestre@cssdufer.gouv.qc.ca',
  'spl@centredesfemmesdemtl.org',
  'emploi@centredesfemmesdemtl.org',
  'orientation@cfemmesplateau.org',
  'info@centreeureka.org',
  'info@horizoncarriere.ca',
  'giniette.grondin@centrejeanbosco.ca',
  'joane.labelle@centrejeanbosco.ca',
  'info@centrelepont.com',
  'info@centrenarive.com',
  'info@r2000.qc.ca',
  'csai@centrecsai.org',
  'info@carrefour-rn.com',
  'emersion@emersion.qc.ca',
  'info@cibleretour.com',
  'clam@bellnet.ca',
  'accueil@citim.org',
  'cre@cremcn.org',
  'ceiq@collectif.qc.ca',
  'COMMUNICATION@CFIQ.CA',
  'emploi@cfiq.ca',
  'communication@cfiq.ca',
  'info@sdem-semo.org',
  'info@cdrhpnq.qc.ca',
  '@connexionemploi',
  //start one company 
  'info@connexionemploi.ca',
  'roberta@connexionemploi.ca',
  'dubec@connexionemploi.ca',
  'pontona@connexionemploi.ca',
  'campbellc@connexionemploi.ca',
  'roygreniera@connexionemploi.ca',
  'cabreraj@connexionemploi.ca',
  //end one company 
  
  'service@coderr.ca',
  'info@connexionemploiressources.com',
  'cremcv@cremcv.com',
  'info@cybercap.qc.ca',
  //start one company
  'reservations@d3pierres.com',
  'parcours@d3pierres.com',
  'info@d3pierres.com',
  //end one company  
  'info@soi-emploi.qc.ca',
  'communications@soi-emploi.qc.ca',
  'reception@dimensiontravail.com',
  'st-jean@quartierdelemploi.ca',
  'employabilite@ateliereclipse.com',
  'chefatelier@ateliereclipse.com',
  'developpement@ateliereclipse.com',
  
  ]
  
  const ListOfNewYorkRecruiter = [
    'www.secretknowledge.us@gmail.com',
    'a.delrio.staffing@gmail.com',
    'jobswithrocky@gmail.com',
    'martha.salas@comeet.com',
    'hima.yidi@gmail.com',
    'rossi.marlene@gmail.com',
    'lmustion@petersan.com',
    'loren.mustion@gmail.com',
    'shaantanu.it.hr@gmail.com',
    'shaantanu@trailblazerit.com',
    'mail-drhmkansal@gmail.com',
    'idannyrios@gmail.com',
    'rebecca.van.riper@gmail.com',
    'danielrobinsontu@gmail.com',
    'rolynch862@gmail.com',
    'rlevi89@gmail.com',
    'surianoa15@gmail.com',
    'watndenver@gmail.com',
    'sethumadhavan.r@gmail.com',
    'sandeep@datagama.com',
    'cianmlodwyer@gmail.com',
    'debwoolridge1@gmail.com',
    'idris.gainam@gmail.com',
    'vinaybcf@gmail.com',
    'victorio.milian@gmail.com',
    'nibya13@gmail.com',
    'danbkaplan@gmail.com',
    'kay.ann.stotler@gmail.com',
    'devonrzg@gmail.com',
    'patelliott16@gmail.com',
    'gayathrikumaresan1508@gmail.com',
    'aridayan24@gmail.com',
    'shahzad.hdev@gmail.com',
    'acalzetti@gmail.com',
    'jayesh121282@gmail.com',
    'jdmmdj@gmail.com',
    'drghiz@gmail.com',
    'niellis@heidrick.com',
    'liberty.hilaryj@gmail.com',
    'laurenzinsky@gmail.com',
    'apri.rokhyadi@sbm-itb.ac.id',
    'michelewilson20@gmail.com',
    'kesdraws@gmail.com',
    'afath8716@gmail.com',
    'dxt2@scarletmail.rutgers.edu',
    'chris.hyland.ch@gmail.com',
    'tgavitticosta@gmail.com',
    'courtneymikush@gmail.com',
    'sharisimmonspeaks@gmail.com',
    'latifmortazavi20@gmail.com',
    'khanhumaira6776@gmail.com',
    'anakamrann@gmail.com',
    'campbell200@gmail.com',
    'glennwoerz@gmail.com',
    'hrbyjdt156@gmail.com',
    'kelseystevens48@gmail.com',
    'kfatema540@gmail.com',
    'lteng9323@gmail.com',
    'gautamdeeksha26@gmail.com',
    'mercedescms21@gmail.com',
    'soyed2323@gmail.com',
    'willybrooke@gmail.com',
    'sap.mikea@gmail.com',
    'rojackrich@gmail.com',
    'andrewleonardis@gmail.com',
    'themortgagehelpclub@gmail.com',
    'info@trylifestory.com',
    'dj.mulzac@gmail.com',
    'margieminnix1@gmail.com',
    'mtierneycasting@gmail.com',
    'sdunlap256@gmail.com',
    'michaelgenao09@gmail.com',
    'wqy20078@gmail.com',
    'noemisafirartist@gmail.com',
    'cibaotravel@gmail.com',
    'taliadov17@gmail.com',
    'ercase1997@gmail.com',
    'his.jeremy@gmail.com',
    'englishmajoroncall@gmail.com',
    'ayushnfreelancing@gmail.com',
    'marlonvar7@gmail.com',
    'murraycarlson11@gmail.com',
    'kelly.oberbillig@gmail.com',
    'djfemmie.intlgrinddjs@gmail.com',
    '7hollywood0@gmail.com',
    'woodruffcatie@gmail.com',
    'burnsworthjiji@gmail.com',
    'zarconsultingllc@gmail.com',
    'u2531235@uel.ac.uk',
    'empeerwellness@gmail.com',
    'jasmine@cieltechnologies.com',
    'sebastian@dulcedo.com',
    'tes.brd@gmail.com',
    'youneshero436@gmail.com',
  ];
  
  //site:linkedin.com/in/ "HR" or "recruiter" "rabat , rabat, morocco" "gmail.com"
  
  
  const ListOfMoroccoRecruiter = [
    'chorouk@harington.fr',
    'chorouk.oudghough@hotmail.com',
    'contact@novancy.com',
    'jobs@novancy.com',
    'tamara.mertens4@gmail.com',
    'kinjal.technowise@gmail.com',
    'hrconnect.com@gmail.com',
    'eric.hwkcom@gmail.com',
    'hr.rasgoc@gmail.com',
    'kaoutar.afif88@gmail.com',
    'amouri.adil@gmail.com',
    'amatltd1991@gmail.com',
    'yassine.guetmy@gmail.com',
    'elyahyaouidrissi@gmail.com',
    'grdmanagement@gmail.com',
    'bogarfawi@gmail.com',
    'hassan.nfaoui@gmail.com',
    'rimammor1@gmail.com',
    'asmaa.hattat@gmail.com',
    'rajouitecno@gmail.com',
    'serghiniidrissimehdi@gmail.com',
    'abdelkrim.benamer@abenpartners.com',
    'fatimazahraelhassi@gmail.com',
    'youssefjadir@gmail.com',
    'abdelouahed.brir@gmail.com',
    'elalamisofya@gmail.com',
    'jawahir.chaabi@gmail.com',
    'abachoukri@gmail.com',
    'otmane.hz@gmail.com',
    'tabloutrans@gmail.com',
    'kenzabennouna97@gmail.com',
    'emmapdodo@gmail.com',
    'saswatikar14@gmail.com',
    'jobstransarabian@gmail.com',
    'mahesh90334@gmail.com',
    'kliff367@gmail.com',
    'novik.olga307@gmail.com',
    'nschwamb@gmail.com',
    'racine.gueye@gmail.com',
    'mgustavoml@gmail.com',
  
  
  ];

const SPMADRID = [
    "nereacastilloasin@gmail.com",
    "mataalexander95@gmail.com",
    "patridiazher@gmail.com",
    "glemus5406@gmail.com",
    "barbara.pieuchot@gmail.com",
    "makarov.alex1997@gmail.com",
    "l8de3studios@gmail.com",
    "luciaconderodriguez95@gmail.com",
    "gbenitca7@gmail.com",
    "estefania.gambin@gmail.com",
    "ssantiago.c@gmail.com",
    "javier@bedfordbailey.com",
    "icuadrado@farmaleaderstalento.com",
    "eduardoayuso@gmail.com",
    "guglielmoluis@gmail.com",
    "mpovedano888@gmail.com",
    "mhernandezcecilia35@gmail.com",
    "alvcavi@gmail.com",
    "aitana.gonzalez.ortiz@gmail.com",
    "aitana.gonzalez@udima.es",
    "aitana.gonzalez@ucm.es",
    "sanlaouna26@gmail.com",
    "valentinshr03@gmail.com",
    "selfa.marisa@gmail.com",
    "camilledigiaimo@gmail.com",
    "internationalbusiness2000@gmail.com",
    "acuesta.1993@gmail.com",
    "lidia.gonzalezharo@gmail.com",
    "peter4realestate@gmail.com",
    "prodelatierra@gmail.com",
    "e.lasarte.z@gmail.com",
    "jlb17751@gmail.com",
    "gaadesignstudio@gmail.com",
    "olivia.ramos.linkedin@gmail.com",
    "pablo@crecetalento.com",
    "dwgenereaux@gmail.com",
    "nada38610@gmail.com",
    "e.legeindre@gmail.com",
    "dharaider.ofc@gmail.com",
    "casascabanasyglampingjm@gmail.com",
    "hofori17@gmail.com",
    "gabriel.gonzalez.villalba@gmail.com",
    "marco.leandri@gmail.com",
    "paul.mateusiak@gmail.com",
    "marinabmaseda@gmail.com",
    "romi3355@gmail.com",
    "barbadosjobs246@gmail.com",
    "vnsourcingfurniture@gmail.com",
    "crewingabiyasa@gmail.com",
    "francisco.espinosa.arroquia@gmail.com",
    "sarah.o.small@gmail.com",
    "dd303ece@gmail.com",
    "sakshi.j33@gmail.com",
    "istomin010593@gmail.com",
    "paloma.martin.martinez@gmail.com",
    "ramesh106.m@gmail.com",
    "aise.21ruipereira@gmail.com",
    "anasalali1@gmail.com",
    "lecostica@gmail.com",
    "kjsdhillon15@gmail.com",
    "jamiepaulchris@gmail.com",
    "byzhanskiy@gmail.com",
    "alexandraaulianta@gmail.com",
    "mc.volken@gmail.com",
    "mercalex.group@gmail.com",
    "meenal2500@gmail.com",
    "sr.oliveira.pt@gmail.com",
    "get2lee@gmail.com",
    "sotsialiconsulting@gmail.com",
    "rupert.jalandoni@gmail.com",
    "rjones297@gmail.com",
    "ordalysmota@gmail.com",
    "vp.alonso19@gmail.com",
    "zakrzewskigreg@gmail.com",
    "vitair.florida@gmail.com",
    "pedrorojas.tutor@outlook.com",
    "jvsomkar7@gmail.com",
    "arquividrios506@gmail.com",
    "roberto.sargo@gmail.com",
    "xia.yue.china@gmail.com",
    "petralazakova@gmail.com"
]


const   GEFrankfurt
= [
    'sashikhan05@gmail.com',
    'sourovsuet@gmail.com',
    'shaun.clyde.theunissen@gmail.com',
    'aasakhare@gmail.com',
    'cpangas2@gmail.com',
    'juhipotdukhe30@gmail.com',
    'sugarlady.amber@gmail.com',
    'holafew@gmail.com',
    'richard.david.michael@gmail.com',
    '1duyguyilmaz1@gmail.com',
    'thai@cavaco.com.vn',
    'ledat.cvc@gmail.com',
    'ramckellin@gmail.com',
    'adelatef930.f@gmail.com',
    'fred.brown.ch@gmail.com',
    'agronaturalpark@gmail.com',
    'paul.nupur16@gmail.com',
    'prasanna.diwadkar@gmail.com',
    'drmartinroberts@gmail.com',
    'michael.r.madison3@gmail.com',
    'vipin682@gmail.com',
    'nagarajyadav868@gmail.com',
    'christan.wale@gmail.com',
    'nicole.dietz.va@gmail.com',
    'brightlightreikiuk@gmail.com',
    'kuryig.20@robcol.k12.tr',
    'lokithor@staff.eslgaming.com',
    'macertacticsesports@gmail.com',
    'freightjerry@gmail.com',
    'tulayvardar95@gmail.com',
    'youneshero436@gmail.com'
  ];
  
  
  const GEBERLINE = [
    'bianca.cmartin@gmail.com',
    'ramizeineddine401@gmail.com',
    'hr.ua2010@gmail.com',
    'abhi1nov95@gmail.com',
    'adshikha19@gmail.com',
    'hrd.india2210@gmail.com',
    'vitorkochdias@gmail.com',
    'oluwatimilehinshonibare42@gmail.com',
    'marcelaoliva89@gmail.com',
    'biancaluz.guimaraes@gmail.com',
    'autret.bastien@gmail.com',
    'hr.samarth5@gmail.com',
    'js.janesee@gmail.com',
    'hartmann.ve@gmail.com',
    'vasilieva.olg2011@yandex.ru',
    'singh.18136@gmail.com',
    'hotelcallingagency@gmail.com',
    'suha.fz@gmail.com',
    'prakashjai990@gmail.com',
    'mariacheretaki@gmail.com',
    'm.pyloridou@gmail.com',
    'danieljurkiewicz12@gmail.com',
    'mobius.comms@gmail.com',
    'anastassiya.ka@gmail.com',
    'arun5l@live.com',
    'mermam0909@gmail.com',
    'hrmilishapetkar@gmail.com',
    'manishkaushik900@gmail.com',
    'brgfpms@gmail.com',
    'ddo-pan@gujarat.gov.in',
    'kathymak83@gmail.com',
    'mwanwey@gmail.com',
    'swati.thecommunityartproject@gmail.com',
    'pastorfemiadeoye@gmail.com',
    'badrudeenissa83@gmail.com',
    'candeladosramos@gmail.com',
    'nurshad19@gmail.com',
    'romior24@gmail.com',
    'ansku.s.kivela@gmail.com',
    'ananshahnila31@gmail.com',
    'internationalsalonacademy@gmail.com',
    'kehindeaina19@gmail.com',
    'chisomuchek@gmail.com',
    '029taka@gmail.com',
    'crisjayavila@gmail.com',
    'fizameshugo@gmail.com',
    'www.mboloukat@gmail.com',
    'raofsarabi0@gmail.com',
    'iyp.croatia@gmail.com',
    'beantdhaliwal800@gmail.com',
    'vesa.kemp@gmail.com',
    'mkosmene@gmail.com',
    'anayahussain168@gmail.com',
    'binukhadka38@gmail.com',
    'acretan@gmail.com',
    'quaderyandsons3@gmail.com',
    'michelle.kolskaar@gmail.com',
    'info@liberanimo.com',
    'iuea2kampala@gmail.com',
    'reetta.alastalo@kotipuhtaaksi.fi',
    'alikikostopoulou@gmail.com',
    'titas.cnf.bd@gmail.com',
    'shantiquiroga@gmail.com',
    'byzhanskiy@gmail.com',
    'fareamist@gmail.com',
    'mitsialissotiris@gmail.com',
    'irismyriel@gmail.com',
    'leesi.gborogbosi@gmail.com',
    'leahkahunde@gmail.com',
    'rashid.ca2000@gmail.com',
    'altapova.a@gmail.com',
    'edwardtaxipanama@gmail.com',
    'jinchoi298@gmail.com',
    'westart725@gmail.com',
    'asf@asfsteelco.com',
    'phuongthuvir@gmail.com',
    'mindaugas.butvila@gmail.com',
    'marcoslzztt@gmail.com',
    'jorgenson.ian@gmail.com',
    'matheus.ciappina@gmail.com',
    'allnxe21@gmail.com',
    'kamilammgs@gmail.com',
    'tuanle28895@gmail.com',
    'hr.nhidang@gmail.com'
  ];
  
  

  const INTERNATIONLEMAILS = [
    'worldwidevacations.hr@gmail.com',
    'careers.yashgroup@gmail.com',
    'karma.zharsh@gmail.com',
    'abcactive@gmail.com',
    'k.langstadt@enzazaden.nl',
    'kk.langstadt@gmail.com',
    'gautam.varun@gmail.com',
    'cv.alkhair2020@gmail.com',
    'alkhairrecrutement@gmail.com',
    'biagiofinocchiaro@gmail.com',
    'lucijakauf571@gmail.com',
    'ahmed85.m@gmail.com',
    'kaushaljuhigupta@gmail.com',
    'josh@jbhtech.org.il',
    'undiscoveredskill@gmail.com',
    'careers.sharpmanpower@gmail.com',
    'globrecs@gmail.com',
    'robin32k@gmail.com',
    'madhumita.arconsultant@gmail.com',
    'farahhrc1@gmail.com',
    'ajeetsnepal@gmail.com',
    'payrollhr2025@gmail.com',
    'muralihr9@gmail.com',
    'knr.abhin@gmail.com',
    'erinmgebo@gmail.com',
    'momezori@gmail.com',
    'bttqd2016@gmail.com',
    'kiran.arconsultant19@gmail.com',
    'blancarodriguezreal@gmail.com',
    'oriannacirigliano1@hotmail.com',
    'namrata.imcjob@gmail.com',
    'raj@aaravrecruitment.com',
    'khouloudmarwen2012@gmail.com',
    'shazia@gmail.com',
    'hr.management786@gmail.com',
    'opal.coelho@gmail.com',
    'iftekhar.cu.hr@gmail.com',
    'trongduylong27081999@gmail.com',
    'trongduylong.hr@gmail.com',
    'zenzsouthafrica@gmail.com',
    'grishkovetskaya@gmail.com',
    'thameemoffshore@gmail.com',
    'martinacl@gmail.com',
    'info@somushr.com',
    'abubackars@gmail.com',
    'harrier.rpo@gmail.com',
    'irfan.nazir88@gmail.com',
    'shlobd@gmail.com',
    'amirraoouf@gmail.com',
    'jself627@gmail.com',
    'lejuriste.ma@gmail.com',
    'tu@interlogic.dk',
    'tetyana.utlova@gmail.com',
    'info.recruitup@gmail.com',
    'dinajpur01@gmail.com',
    'namemeny@gmail.com',
    'a@mindsmatch.io',
    'saibari.ismail@gmail.com',
    'nisr_tn@htomail.com',
    'almahmeedagency@gmail.com',
    'ar9021071@gmail.com',
    'beckfordbuildes@gmail.com',
    'waseemkhan472829@gmail.com',
    'pmsharma1985@gmail.com',
    'nosole16@gmail.com',
    'ibrahimlazol@gmail.com',
    'ninfa9981@gmail.com',
    'nadjibenine@gmail.com',
    'michelle.oneill1001@gmail.com',
    'alexszabo1122@gmail.com',
    'liezamonaya12@gmail.com',
    'goparaju.bhargav7@gmail.com',
    'stfreshfoods@gmail.com',
    'navitagupta07@gmail.com',
    'saiful.manage@gmail.com',
    'kaswaconsulting@gmail.com',
    'ildikohorvathhungary@gmail.com',
    'jannie.hestehave@gmail.com',
    'amenyritej@gmail.com',
    'sreeamruthk@gmail.com',
    'afanazeem@gmail.com',
    'nafiu.mustafa@gmail.com',
    'nifrasports3@gmail.com',
    'margarita.mccracken@gmail.com',
    'kinza6096@gmail.com',
    'advanap@gmail.com',
    'movimientociapanam@gmail.com',
    'eduardogarciajm@gmail.com',
    'marjaana.murtomaa@gmail.com',
    'bouchaouir.sara@gmail.com',
    'andybellcareers@gmail.com',
    'ghmahesh006@gmail.com',
    'hello@canadapr.vn',
    'mandla.khambule@khambs.co.za',
    'marcdingo2@gmail.com',
    'palazzidaniela476@gmail.com',
    'asimk99@gmail.com',
    'hamdyyousry4@gmail.com',
    'flavia.scukier@gmail.com',
    'ahmemdemad@gmail.com',
    'abdelkrim.benamer@abenpartners.com',
    'ya.nabieva@gmail.com',
    'drsbtool@gmail.com',
    'm.kareckiene@gmail.com',
    'maharajacorporation@gmail.com',
    'janinethockey@gmail.com',
    'ngocdiep.ba.dn@gmail.com',
    'parthtulcidas.gex@gmail.com',
    'samsulalam.hr@gmail.com',
    'shahzeb.irco@gmail.com',
    'juttfarah06@gmail.com',
    'malaysia@theriveroverseas.com',
    'lejomarcsshr@gmail.com',
    'jinja7@gmail.com',
    'melvinmarasigan.ph@gmail.com',
    'tej.kgill@gmail.com',
    'oualiibrahim202085@gmail.com',
    'seleccionhr.msc@gmail.com',
    'mhykhae@gmail.com',
    'mogaffa@gmail.com',
    'nahidas636@gmail.com',
    'brunomarques2608@gmail.com',
    'ksahiringco@gmail.com',
    'waqarusg@gmail.com',
    'trandinhtinh5155@gmail.com',
    'adelsa587@gmail.com',
    'borsha.koli@gmail.com',
    'ayesha@gainint.com',
    'nour.mohamed19888@gmail.com',
    'noemisafirartist@gmail.com',
    'youneshero436@gmail.com',
    'cvgrccin@gmail.com'
  ];
  
  // Now you can use the karmaZharshEmails array in your code as needed.
  const MATANGER = [
    // 'khalilboutaina@gmail.com',
    // 'youness.lecheguer@gmail.com',
    // 'sonicempire2020@gmail.com',
    // 'ae.fadilis@gmail.com',
    // 'jounaid.mohamed@gmail.com',
    // 'youssef.elfakir@hilton.com',
    // 'wissamemouhssine2014@gmail.com',
    // 'zabdi@gmail.com',
    // 'ahlameelgannouni@gmail.com',
    // 'marocexperiencetour@gmail.com',
    // 'elouarzazimouad@gmail.com',
    // 'benhmadabdella@gmail.com',
    // 'mustaphahaour@gmail.com',
    // 'barkoukahmad@gmail.com',
    // 'kjamali74@gmail.com',
    // 'lazouni.soumia.e1@gmail.com',
    // 'jaggarlarbi@gmail.com',
    // 'youssefadid@gmail.com',
    // 'benahmedkhalil3@gmail.com',
    // 'aelammari415@gmail.com',
    // 'badrandahik3@gmail.com',
    // 'abdelbar.negoce@gmail.com',
    // 'marwa.darouichi@gmail.com',
    // 'omaramgoun2017@gmail.com',
    // 'jamal.barrigha@gmail.com',
    // 'mamadybeyla45@gmail.com',
    // 'overseashrservices@gmail.com',
    // 'imad.zafri.1992@gmail.com',
    // 'youssefjadir@gmail.com',
    // 'mohamedabouhussein@gmail.com',
    // 'haidimohamed@gmail.com',
    // 'zohraraib9@gmail.com',
    // 'eddouyby.1088@gmail.com',
    // 'talbihamza180@gmail.com',
    // 'abdelfettah.lazrak@gmail.com',
    // 'reklaouihanae@gmail.com',
    // 'abdellahstaitay@gmail.com',
    // 'mohcinrifki@gmail.com',
    // 'younesselorjani604@gmail.com',
    // 'gargiagpaulo@gmail.com',
    // 'bedoui.fatima.zohra@gmail.com',
    // 'lazimikhawla66@gmail.com',
    // 'saidmakboul2016@gmail.com',
    // 'najwaoukelna@gmail.com',
    // 'medamineomari59@gmail.com',
    // 'abdessadeq.said@gmail.com',
    // 'erram.rabii77@gmail.com',
    // 'mohameddourgali727@gmail.com',
    // 'chafouiahlam@gmail.com',
    // 'mohamed.moujahid0@gmail.com',
    'hichambouftih1@gmail.com',
    'hamza.hafidi@gmail.com',
    'hamman.yassine@gmail.com',
    'eveil.thinktank@gmail.com',
    'erosbonatti@gmail.com',
    'aryaisole34@gmail.com',
    'semacrenes@gmail.com',
    'bu.coordination@gmail.com',
    'ondrej.navrat@gmail.com',
    'mail-drhmkansal@gmail.com'
  ];
  
  // Now you can use the MATANGER array in your code as needed.
  


module.exports = {
  BestWebAgencyInRabat,
    AU,
    MATANGER,
    GEBERLINE,
    INTERNATIONLEMAILS,
    GEFrankfurt,
    SPMADRID,
    UKLONDONEMAILS,
    FRPARIS,
    UKMANCHESTER,
    emailArray,
    ListOfCompaniesOfCanada,
    ListOfMoroccoRecruiter,
    ListOfNewYorkRecruiter,
    NewListOfCanada
}


