// userConstants.js
export const SET_MENU_OPEN = 'SET_MENU_OPEN';
export const SET_PENDING_REQUESTS = 'SET_PENDING_REQUESTS';
export const SET_APPROVED_REQUESTS = 'SET_APPROVED_REQUESTS'
export const SET_REJECTED_REQUESTS = 'SET_REJECTED_REQUESTS'